### ISSUE TITLE
Capcalc docker package version incompatibility

### ISSUE THREAD

**Issue by pstewa** [bbfrederick/capcalc#5]
**Describe the bug**

capfromtcs will not run within docker container.
capfromtcs program in package is written for an older version of rapidtide, possibly 1.9.3

**To Reproduce**

Run capfromtcs after pulling docker container.

**My Setup**

Singularity 3.5.2
singularity pull docker://fredericklab/capcalc

**Comment by bbfrederick** [comment]
Ok, over the last week, I've tracked down and  eliminated MANY issues with the automated deployment process to pypi, readthedocs, and Dockerhub.  I think I just got the last one (the "latest" build wasn't actually being rebuilt to the latest version).  Give it a try now.

**Comment by pstewa** [comment]
Thanks for spending your time and energy getting this working!

There is an error in the new build. A dependency of capfromtcs,' _gittag.py', is now missing from /src/capcalc/capcalc

Otherwise everything looks correct!

Best,
Paul


________________________________

**Comment by bbfrederick** [comment]
Hmm.  I can't find any reference to that file (which is why I removed it).

Can you send the full error message so I can try to track down what's looking for it?

**Comment by pstewa** [comment]
I rebuilt the container and it works fine! I think I had something cached that was causing an issue with the build, and creating a reference to gittag in an init.py file that had been removed in the current version.
